"""
listen_all.py — every E(k,n) in toussaint-rhythms.json as a WAV, plus an index.
The fixture is data a sequencer builder copies; this is what each row sounds like, so a
reader of the published fixture can hear E(5,16) and check the 17-symbol misprint by ear.
Patterns are read from the fixture (generated by bjorklund.py, not typed); nothing here
is transcribed. Output: out/all/E<k>-<n>.wav and out/all/INDEX.md.
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from listen import render, write

if __name__ == "__main__":
    here = os.path.dirname(__file__)
    fx = json.load(open(os.path.join(here, "toussaint-rhythms.json"), encoding="utf8"))
    outdir = os.path.join(here, "out", "all"); os.makedirs(outdir, exist_ok=True)
    rows = []
    for r in fx["rhythms"]:
        k, n = r["k"], r["n"]
        reps = max(4, 32 // n)                      # short cycles repeat more
        s = render(r["onsets"], n, bpm=96, reps=reps)
        fn = f"E{k}-{n}.wav"
        write(os.path.join(outdir, fn), s)
        rows.append(f"| E({k},{n}) | `{r['bjorklund']}` | {r['relation']} | {r['name'] or ''} | {fn} |")
        print(f"E({k:>2},{n:>2}) {r['bjorklund']:<26} {r['relation']:<9} {r['name'] or ''}")
    idx = ["# Every rhythm in toussaint-rhythms.json, rendered", "",
           f"Source fixture: `{fx['source']}`; generated by `{fx['generated_by']}`. 96 bpm, one pulse = a sixteenth.", "",
           "| rhythm | pattern (bjorklund) | vs paper | name | file |", "|---|---|---|---|---|", *rows]
    open(os.path.join(outdir, "INDEX.md"), "w", encoding="utf8").write("\n".join(idx) + "\n")
    print(f"\n{len(rows)} files + INDEX.md in {outdir}")
