"""
Emit a machine-readable test fixture: every E(k,n) rhythm Toussaint names, with the
pattern independently generated by Bjorklund rather than transcribed from the paper,
the paper's printed string beside it, and a flag where they disagree.

Why this is worth existing: people implementing Euclidean rhythm generators (Eurorack
firmware, TidalCycles, Sonic Pi, a hundred hobby sequencers) copy the table out of that
paper to test against. One row in it is misprinted with an extra rest. Anyone who
copies E(5,16) as printed gets a 17-step pattern where they wanted 16, and their test
fixture is then wrong in a way their implementation will be blamed for.

The fixture is the artifact. The finding is only the reason it exists.
"""
import io
import json
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")
from bjorklund import bjorklund, as_string, intervals, maximally_even, is_rotation_of

text = io.open("toussaint2005.txt", encoding="utf-8").read()
CLAIM = re.compile(r"E\(\s*(\d+)\s*,\s*(\d+)\s*\)\s*=?\s*\[([x\s.]+)\]([^\n\[]{0,140})")

# names as the paper gives them, keyed by (k, n)
seen = {}
for m in CLAIM.finditer(text):
    k, n = int(m.group(1)), int(m.group(2))
    printed = m.group(3).replace(" ", "").strip()
    note = " ".join(m.group(4).split())
    if not printed or set(printed) - {"x", "."}:
        continue
    if (k, n) not in seen or len(note) > len(seen[(k, n)][1]):
        seen[(k, n)] = (printed, note)


def name_from(note):
    """pull a plausible rhythm name out of the paper's prose"""
    n = re.sub(r"^[=\s]*", "", note)
    n = re.sub(r"^\(.*?\)\s*", "", n)
    m = re.match(r"is (?:the |a |another |an )?([^.\[]{3,60}?)(?: pattern| rhythm| discussed| used| \[|\.|,)", n)
    return m.group(1).strip() if m else None


rows = []
for (k, n), (printed, note) in sorted(seen.items()):
    generated = as_string(bjorklund(k, n))

    # three distinct relationships, and collapsing them would make this fixture
    # cry wolf on four correct rows:
    #   exact     — algorithm output and printed string are identical
    #   rotation  — same necklace, different starting onset. The paper says so
    #               explicitly for these ("when started on the second onset") and the
    #               printed orientation is the musically meaningful one.
    #   MISPRINT  — genuinely wrong, and there is exactly one.
    if printed == generated:
        rel, note_txt = "exact", None
    elif len(printed) == n and is_rotation_of(list(printed), list(generated)):
        rel, note_txt = "rotation", (
            f"Same necklace, different starting onset. Bjorklund emits {generated}; "
            f"the paper prints {printed}, which is the orientation the rhythm is "
            f"played from. Neither is wrong — pick by what you need.")
    else:
        rel, note_txt = "MISPRINT", (
            f"Toussaint 2005 prints {len(printed)} symbols for E({k},{n}), which has "
            f"{n}. The paper's own interval vector on the same line is correct and "
            f"disagrees with its ASCII. Use `bjorklund`, not `as_printed`.")

    rows.append({
        "k": k,
        "n": n,
        "bjorklund": generated,            # algorithm output, canonical rotation
        "as_printed": printed,             # the paper's orientation, verbatim
        "relation": rel,
        "onsets": [i for i, c in enumerate(generated) if c == "x"],
        "intervals": intervals(bjorklund(k, n)),
        "maximally_even": maximally_even(bjorklund(k, n)),
        "name": name_from(note),
        "note": note_txt,
    })

out = {
    "what": "Euclidean rhythms E(k,n) named in Toussaint (2005), independently generated",
    "source": "Godfried T. Toussaint, 'The Euclidean Algorithm Generates Traditional "
              "Musical Rhythms', BRIDGES 2005. https://cgm.cs.mcgill.ca/~godfried/publications/banff.pdf",
    "generated_by": "Bjorklund's algorithm, implemented from its description in "
                    "bjorklund.py, not copied from a library and not transcribed from the paper",
    "how_to_check": "Run your own E(k,n) and compare to `bjorklund`. `as_printed` is "
                    "the paper's string verbatim; where `relation` is 'rotation' the two "
                    "are the same necklace started at a different onset and both are "
                    "correct. Exactly one row is a genuine misprint.",
    "relation_counts": {r: sum(1 for x in rows if x["relation"] == r)
                        for r in ("exact", "rotation", "MISPRINT")},
    "misprints": [f"E({r['k']},{r['n']})" for r in rows if r["relation"] == "MISPRINT"],
    "rhythms": rows,
}

io.open("toussaint-rhythms.json", "w", encoding="utf-8").write(
    json.dumps(out, indent=2, ensure_ascii=False) + "\n")

counts = out["relation_counts"]
print(f"wrote toussaint-rhythms.json — {len(rows)} rhythms: "
      f"{counts['exact']} exact, {counts['rotation']} rotation, {counts['MISPRINT']} misprint")
for r in rows:
    flag = {"exact": "", "rotation": "   (rotation — both correct)",
            "MISPRINT": "   <-- MISPRINT in the paper"}[r["relation"]]
    print(f"  E({r['k']},{r['n']})".ljust(11) + f"{r['bjorklund']:<26} {r['name'] or ''}{flag}")
